name: flutter_webview
description: "Basic Flutter webview app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.7.0
  firebase_core: ^3.14.0
  firebase_remote_config: ^5.4.5
  flutter_native_splash: ^2.4.6
  get: 4.6.6
  json_annotation: ^4.7.0
  google_fonts: ^4.0.0
  get_it: ^7.2.0
  auto_route: ^8.1.3
  sizer: ^2.0.15
  flutter_flavor: ^3.1.4

  loading_indicator:
    git:
      url: https://github.com/TinoGuo/loading_indicator.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  flutter_lints: ^5.0.0
  auto_route_generator: ^8.0.0
  json_serializable: ^6.5.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
